// Every number on the Health tab traces to one of these (D55; research and verification in .claude/habits.md).
// PURE: no imports, node-runnable.

export type Source = {
  /** short label shown under a number */
  cite: string;
  /** full citation */
  full: string;
  url: string;
  /** who was studied (so the app can say "in Indian data" / "Western data") */
  who: string;
  india: "yes" | "partly" | "no";
};

export const SOURCES = {
  hackshaw2018: {
    cite: "Hackshaw et al., BMJ 2018",
    full: "Hackshaw A, Morris JK, Boniface S, Tang JL, Milenković D. Low cigarette consumption and risk of coronary heart disease and stroke: meta-analysis of 141 cohort studies in 55 study reports. BMJ 2018;360:j5855",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC5781309/",
    who: "141 cohorts, mostly Europe, North America and East Asia",
    india: "no",
  },
  banks2019: {
    cite: "Banks et al., BMC Med 2019",
    full: "Banks E, Joshy G, Korda RJ, et al. Tobacco smoking and risk of 36 cardiovascular disease subtypes: fatal and non-fatal outcomes in a large prospective Australian study. BMC Med 2019;17:128",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC6607519/",
    who: "188,167 adults aged 45+, Australia, 2006–2015",
    india: "no",
  },
  doll2004: {
    cite: "Doll et al., BMJ 2004",
    full: "Doll R, Peto R, Boreham J, Sutherland I. Mortality in relation to smoking: 50 years' observations on male British doctors. BMJ 2004;328:1519",
    url: "https://pubmed.ncbi.nlm.nih.gov/15213107/",
    who: "34,439 male British doctors, 1951–2001",
    india: "no",
  },
  jha2008: {
    cite: "Jha et al., NEJM 2008",
    full: "Jha P, Jacob B, Gajalakshmi V, et al. A nationally representative case-control study of smoking and death in India. N Engl J Med 2008;358:1137-47",
    url: "https://pubmed.ncbi.nlm.nih.gov/18272886/",
    who: "India, nationally representative, deaths 2001–2003, ages 30–69",
    india: "yes",
  },
  gupta2005: {
    cite: "Gupta et al., Int J Epidemiol 2005",
    full: "Gupta PC, Pednekar MS, Parkin DM, Sankaranarayanan R. Tobacco associated mortality in Mumbai (Bombay) India. Results of the Bombay Cohort Study. Int J Epidemiol 2005;34:1395-1402",
    url: "https://pubmed.ncbi.nlm.nih.gov/16249218/",
    who: "99,570 adults aged 35+, Mumbai, 1992–1999",
    india: "yes",
  },
  pednekar2011: {
    cite: "Pednekar et al., Cancer Causes Control 2011",
    full: "Pednekar MS, Gupta PC, Yeole BB, Hébert JR. Cancer Causes Control 2011;22(6):859-68 (Mumbai cohort: cancer incidence by tobacco habit)",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3756904/",
    who: "87,222 men, Mumbai, 1991–2003",
    india: "yes",
  },
  possenti2026: {
    cite: "Possenti et al., Oncol Rev 2026",
    full: "Possenti I, Miotti S, Gallus S, et al. Smoking and oral and pharyngeal cancer: a comprehensive dose-response meta-analysis. Oncol Rev 2025;19:1672607",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12865294/",
    who: "115 studies worldwide, incl. 17 from India",
    india: "partly",
  },
  rota2024: {
    cite: "Rota et al., Gastric Cancer 2024",
    full: "Rota M, Possenti I, Valsassina V, et al. Dose-response association between cigarette smoking and gastric cancer risk: a systematic review and meta-analysis. Gastric Cancer 2024;27:197-209",
    url: "https://pubmed.ncbi.nlm.nih.gov/38231449/",
    who: "205 studies worldwide, incl. 12 from India",
    india: "partly",
  },
  lugo2018: {
    cite: "Lugo et al., Eur J Cancer 2018",
    full: "Lugo A, Peveri G, Bosetti C, et al. Strong excess risk of pancreatic cancer for low frequency and duration of cigarette smoking: a comprehensive review and meta-analysis. Eur J Cancer 2018;104:117-126",
    url: "https://pubmed.ncbi.nlm.nih.gov/30347287/",
    who: "78 studies worldwide",
    india: "no",
  },
  liu2019: {
    cite: "Liu et al., Crit Rev Oncol Hematol 2019",
    full: "Liu X, Peveri G, Bosetti C, et al. Dose-response relationships between cigarette smoking and kidney cancer: a systematic review and meta-analysis. Crit Rev Oncol Hematol 2019;142:86-93",
    url: "https://pubmed.ncbi.nlm.nih.gov/31387065/",
    who: "56 studies worldwide",
    india: "no",
  },
  scala2023: {
    cite: "Scala et al., J Epidemiol 2023",
    full: "Scala M, Bosetti C, Bagnardi V, Possenti I, Specchia C, Gallus S, Lugo A. Dose-response relationships between cigarette smoking and breast cancer risk: a systematic review and meta-analysis. J Epidemiol 2023;33(12):640-648",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC10635814/",
    who: "169 studies worldwide",
    india: "no",
  },
  pan2015: {
    cite: "Pan et al., Lancet Diabetes Endocrinol 2015",
    full: "Pan A, Wang Y, Talaei M, Hu FB, Wu T. Relation of active, passive, and quitting smoking with incident type 2 diabetes: a systematic review and meta-analysis. Lancet Diabetes Endocrinol 2015;3:958-67",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4656094/",
    who: "88 prospective studies, nearly 6 million people",
    india: "no",
  },
  zhong2015: {
    cite: "Zhong et al., PLoS One 2015",
    full: "Zhong G, Wang Y, Zhang Y, Guo JJ, Zhao Y. Smoking is associated with an increased risk of dementia: a meta-analysis of prospective cohort studies with investigation of potential effect modifiers. PLoS One 2015;10:e0118333",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4357455/",
    who: "37 cohort studies",
    india: "no",
  },
  leite2018: {
    cite: "Leite et al., Am J Prev Med 2018",
    full: "Leite FRM, Nascimento GG, Scheutz F, López R. Effect of smoking on periodontitis: a systematic review and meta-regression. Am J Prev Med 2018;54:831-841",
    url: "https://pubmed.ncbi.nlm.nih.gov/29656920/",
    who: "14 prospective studies",
    india: "no",
  },
  kanis2005: {
    cite: "Kanis et al., Osteoporos Int 2005",
    full: "Kanis JA, Johnell O, Oden A, et al. Smoking and fracture risk: a meta-analysis. Osteoporos Int 2005;16:155-62",
    url: "https://pubmed.ncbi.nlm.nih.gov/15175845/",
    who: "10 cohorts, 59,232 people",
    india: "no",
  },
  cao2014: {
    cite: "Cao et al., J Sex Med 2014",
    full: "Cao S, Gan Y, Dong X, Liu J, Lu Z. Association of quantity and duration of smoking with erectile dysfunction: a dose-response meta-analysis. J Sex Med 2014;11:2376-84",
    url: "https://pubmed.ncbi.nlm.nih.gov/25052869/",
    who: "1 cohort + 9 cross-sectional studies, 50,360 men",
    india: "no",
  },
  jackson2025: {
    cite: "Jackson, Jarvis & West, Addiction 2025",
    full: "Jackson SE, Jarvis MJ, West R. The price of a cigarette: 20 minutes of life? Addiction 2025;120:810-812",
    url: "https://pubmed.ncbi.nlm.nih.gov/39734064/",
    who: "British Doctors Study + Million Women Study (UK)",
    india: "no",
  },
  teo2006: {
    cite: "INTERHEART, Lancet 2006",
    full: "Teo KK, Ounpuu S, Hawken S, et al. Tobacco use and risk of myocardial infarction in 52 countries in the INTERHEART study: a case-control study. Lancet 2006;368:647-58",
    url: "https://pubmed.ncbi.nlm.nih.gov/16920470/",
    who: "12,461 heart-attack cases and 14,637 controls, 52 countries incl. South Asia",
    india: "partly",
  },
  gupta2014: {
    cite: "Gupta & Johnson, PLoS One 2014",
    full: "Gupta B, Johnson NW. Systematic review and meta-analysis of association of smokeless tobacco and of betel quid without tobacco with incidence of oral cancer in South Asia and the Pacific. PLoS One 2014;9:e113385",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4239077/",
    who: "Studies from India, Pakistan, Taiwan, Papua New Guinea",
    india: "yes",
  },
  guha2014: {
    cite: "Guha et al., Int J Cancer 2014",
    full: "Guha N, Warnakulasuriya S, Vlaanderen J, Straif K. Betel quid chewing and the risk of oral and oropharyngeal cancers: a meta-analysis with implications for cancer control. Int J Cancer 2014;135:1433-43",
    url: "https://pubmed.ncbi.nlm.nih.gov/24302487/",
    who: "31 studies of betel quid with tobacco, mostly Indian subcontinent",
    india: "yes",
  },
  primack2016: {
    cite: "Primack et al., Public Health Rep 2016",
    full: "Primack BA, Carroll MV, Weiss PM, et al. Systematic review and meta-analysis of inhaled toxicants from waterpipe and cigarette smoking. Public Health Rep 2016;131:76-85",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4716475/",
    who: "17 laboratory and human studies",
    india: "no",
  },
  nasem2018: {
    cite: "US National Academies 2018",
    full: "National Academies of Sciences, Engineering, and Medicine. Public Health Consequences of E-Cigarettes. Washington, DC: The National Academies Press; 2018",
    url: "https://doi.org/10.17226/24952",
    who: "Review of all published e-cigarette evidence to 2017",
    india: "no",
  },
  sg1990: {
    cite: "US Surgeon General 1990",
    full: "US Department of Health and Human Services. The Health Benefits of Smoking Cessation: a report of the Surgeon General. DHHS Pub No. (CDC) 90-8416, 1990",
    url: "https://www.cdc.gov/mmwr/preview/mmwrhtml/00001801.htm",
    who: "Review of cessation studies",
    india: "no",
  },
  kambam1986: {
    cite: "Kambam et al., Anesth Analg 1986",
    full: "Kambam JR, Chen LH, Hyman SA. Effect of short-term smoking halt on carboxyhemoglobin levels and P50 values. Anesth Analg 1986;65:1186-8",
    url: "https://pubmed.ncbi.nlm.nih.gov/3767017/",
    who: "15 smokers of 1–2 packs a day",
    india: "no",
  },
  duncan2019: {
    cite: "Duncan et al., JAMA 2019",
    full: "Duncan MS, Freiberg MS, Greevy RA Jr, et al. Association of smoking cessation with subsequent risk of cardiovascular disease. JAMA 2019;322:642-650",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC6704757/",
    who: "Framingham Heart Study, heavy smokers (20+ pack-years)",
    india: "no",
  },
  tindle2018: {
    cite: "Tindle et al., JNCI 2018",
    full: "Tindle HA, Stevenson Duncan M, Greevy RA, et al. Lifetime smoking history and risk of lung cancer: results from the Framingham Heart Study. J Natl Cancer Inst 2018;110:1201-1207",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC6235683/",
    who: "Framingham Heart Study, heavy smokers (21.3+ pack-years)",
    india: "no",
  },
  godtfredsen2005: {
    cite: "Godtfredsen et al., JAMA 2005",
    full: "Godtfredsen NS, Prescott E, Osler M. Effect of smoking reduction on lung cancer risk. JAMA 2005;294:1505-10",
    url: "https://pubmed.ncbi.nlm.nih.gov/16189363/",
    who: "19,714 adults, Copenhagen, 31 years of follow-up",
    india: "no",
  },
  aubin2012: {
    cite: "Aubin et al., BMJ 2012",
    full: "Aubin HJ, Farley A, Lycett D, Lahmek P, Aveyard P. Weight gain in smokers after quitting cigarettes: meta-analysis. BMJ 2012;345:e4439",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3393785/",
    who: "62 quit-smoking trials, mostly USA and Europe",
    india: "no",
  },
  hashibe2009: {
    cite: "Hashibe et al., CEBP 2009",
    full: "Hashibe M, Brennan P, Chuang SC, et al. Interaction between tobacco and alcohol use and the risk of head and neck cancer: pooled analysis in the INHANCE consortium. Cancer Epidemiol Biomarkers Prev 2009;18:541-50",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3051410/",
    who: "17 case-control studies, 11,221 cases (India not included)",
    india: "no",
  },
  wood2018: {
    cite: "Wood et al., Lancet 2018",
    full: "Wood AM, Kaptoge S, Butterworth AS, et al. Risk thresholds for alcohol consumption: combined analysis of individual-participant data for 599 912 current drinkers in 83 prospective studies. Lancet 2018;391:1513-23",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC5899998/",
    who: "599,912 current drinkers, 19 high-income countries",
    india: "no",
  },
  gbd2022: {
    cite: "GBD 2020 Alcohol Collaborators, Lancet 2022",
    full: "GBD 2020 Alcohol Collaborators. Population-level risks of alcohol consumption by amount, geography, age, sex, and year. Lancet 2022;400:185-235 (appendix 2, Table S1: South Asia)",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC9289789/",
    who: "Global Burden of Disease, South Asia region values",
    india: "partly",
  },
  bagnardi2015: {
    cite: "Bagnardi et al., Br J Cancer 2015",
    full: "Bagnardi V, Rota M, Botteri E, et al. Alcohol consumption and site-specific cancer risk: a comprehensive dose-response meta-analysis. Br J Cancer 2015;112:580-93",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4453639/",
    who: "572 studies, 486,538 cancer cases",
    india: "partly",
  },
  roerecke2017: {
    cite: "Roerecke et al., Lancet Public Health 2017",
    full: "Roerecke M, Kaczorowski J, Tobe SW, et al. The effect of a reduction in alcohol consumption on blood pressure: a systematic review and meta-analysis. Lancet Public Health 2017;2:e108-20",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC6118407/",
    who: "36 trials, 2,865 people",
    india: "no",
  },
  jiang2022: {
    cite: "Jiang et al., Front Cardiovasc Med 2022",
    full: "Jiang H, Mei X, Jiang Y, et al. Alcohol consumption and atrial fibrillation risk: an updated dose-response meta-analysis of over 10 million participants. Front Cardiovasc Med 2022;9:979982",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC9561500/",
    who: "13 cohorts, 10 million people (mostly Korea)",
    india: "no",
  },
  roerecke2019: {
    cite: "Roerecke et al., Am J Gastroenterol 2019",
    full: "Roerecke M, Vafaei A, Hasan OSM, et al. Alcohol consumption and risk of liver cirrhosis: a systematic review and meta-analysis. Am J Gastroenterol 2019;114:1574-86",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC6776700/",
    who: "9 studies, 2.6 million people (US, Europe, China)",
    india: "no",
  },
  hamajima2002: {
    cite: "Hamajima et al., Br J Cancer 2002",
    full: "Collaborative Group on Hormonal Factors in Breast Cancer. Alcohol, tobacco and breast cancer: collaborative reanalysis of individual data from 53 epidemiological studies. Br J Cancer 2002;87:1234-45",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC2562507/",
    who: "53 studies, 58,515 women with breast cancer",
    india: "no",
  },
  ncdir2018: {
    cite: "ICMR-NCDIR, NNMS 2017–18",
    full: "ICMR-National Centre for Disease Informatics and Research. National Noncommunicable Disease Monitoring Survey 2017–18 (alcohol factsheet)",
    url: "https://www.ncdirindia.org/Downloads/Alcohol_Awareness.pdf",
    who: "Government of India survey",
    india: "yes",
  },
  who2019: {
    cite: "WHO CVD risk charts, Lancet Glob Health 2019",
    full: "WHO CVD Risk Chart Working Group. World Health Organization cardiovascular disease risk charts: revised models to estimate risk in 21 global regions. Lancet Glob Health 2019;7:e1332-45 (non-laboratory chart, South Asia; = WHO HEARTS 2020 Annex 3)",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC7025029/",
    who: "Derived in 85 cohorts, recalibrated to South Asia (India, Bangladesh, Bhutan, Nepal, Pakistan)",
    india: "partly",
  },
  joseph2018: {
    cite: "INTERHEART score, Joseph et al., Heart 2018",
    full: "McGorrian C, Yusuf S, Islam S, et al. Eur Heart J 2011;32:581-9; non-laboratory score validated and recalibrated by region in Joseph P, Yusuf S, Lee SF, et al. Heart 2018;104:581-7",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC5861396/",
    who: "PURE study, 100,475 people in 17 countries incl. 12,130 in South Asia",
    india: "yes",
  },
  mohan2005: {
    cite: "Indian Diabetes Risk Score, Mohan et al. 2005",
    full: "Mohan V, Deepa R, Deepa M, Somannavar S, Datta M. A simplified Indian Diabetes Risk Score for screening for undiagnosed diabetic subjects. J Assoc Physicians India 2005;53:759-63; national validation: Deepa M et al. (ICMR-INDIAB-15), Indian J Med Res 2023;157:239-49",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC10438401/",
    who: "Chennai (CURES) and 113,043 adults across India (ICMR-INDIAB)",
    india: "yes",
  },
  who2004: {
    cite: "WHO Expert Consultation, Lancet 2004",
    full: "WHO Expert Consultation. Appropriate body-mass index for Asian populations and its implications for policy and intervention strategies. Lancet 2004;363:157-63",
    url: "https://pubmed.ncbi.nlm.nih.gov/14726171/",
    who: "Asian populations",
    india: "yes",
  },
  ish2020: {
    cite: "ISH 2020 hypertension guideline",
    full: "Unger T, Borghi C, Charchar F, et al. 2020 International Society of Hypertension Global Hypertension Practice Guidelines. Hypertension 2020;75:1334-57 (Tables 2 and 5: home BP ≥135/85; 3–7 days, morning and evening, first day discarded)",
    url: "https://pubmed.ncbi.nlm.nih.gov/32370572/",
    who: "Global guideline",
    india: "partly",
  },
  igh2019: {
    cite: "Indian Guidelines on Hypertension-IV 2019",
    full: "Shah SN, Munjal YP, Kamath SA, et al. Indian Guidelines on Hypertension-IV (2019). J Hum Hypertens 2020;34:745-58 (Table 4: self / home BP ≥135/85)",
    url: "https://pubmed.ncbi.nlm.nih.gov/32427886/",
    who: "Indian guideline",
    india: "yes",
  },
  icmr2026: {
    cite: "ICMR Standard Treatment Workflow 2026",
    full: "Indian Council of Medical Research. Standard Treatment Workflow: Hypertension in Adults (ICD-11 BA00), May 2026 (urgency ≥180 and/or ≥120 mmHg; red-flag symptoms)",
    url: "https://www.icmr.gov.in/icmrobject/uploads/STWs/1778941063_hypertensioninadults_final.pdf",
    who: "Government of India (ICMR / DHR, MoHFW)",
    india: "yes",
  },
  misra2025: {
    cite: "Misra et al., Diabetes Metab Syndr 2025",
    full: "Misra A, Vikram NK, Ghosh A, et al. Revised definition of obesity in Asian Indians living in India. Diabetes Metab Syndr 2025;19:102989 (and the 2009 consensus, J Assoc Physicians India 2009;57:163-70)",
    url: "https://doi.org/10.1016/j.dsx.2024.102989",
    who: "Indian expert consensus (118 experts)",
    india: "yes",
  },
} satisfies Record<string, Source>;

export type SourceId = keyof typeof SOURCES;
